blueprint:
  name: Mark as Away
  description: Make Presence detection not so Binary - Away.
  domain: automation
  input:
    rich_selector:
      name: Rich Location Selector
      selector:
        target:
          entity:
            domain: input_select

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input rich_selector
  to: 'Just Left'
  for:
    minutes: 10
action:
- service: input_select.select_option
  data:
    entity_id: !input rich_selector
    option: Away
