blueprint:
  name: Mark as Away
  description: Make Presence detection not so Binary - Away.
  domain: automation
  source_url: https://github.com/tomerghelber/homeassistant/edit/main/blueprints/not_binary_presence_detection_away.yaml
  input:
    rich_selector:
      name: Rich Location Selector
      selector:
        target:
          entity:
            domain: input_select
     wait_before_away:
       name: Wait Before Away
       description: How much to wait before changing to away in minutes.
       selector:
         number:
           min: 1
           max: 15
           unit_of_measurement: minutes

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input rich_selector
  to: 'Just Left'
  for:
    minutes: !input wait_before_away
action:
- service: input_select.select_option
  data:
    entity_id: !input rich_selector
    option: Away
