blueprint:
  name: Mark as Just Arrived
  description: Make Presence detection not so Binary - Just Arrived.
  domain: automation
  source_url: https://github.com/tomerghelber/homeassistant/edit/main/blueprints/not_binary_presence_detection_just_arrived.yaml
  input:
    tracker:
      name: Tracker
      selector:
        entity:
          domain: device_tracker
    rich_selector:
      name: Rich Location Selector
      selector:
        target:
          entity:
            domain: input_select

trigger:
- platform: state
  entity_id: !input tracker
  from: 'not_home'
  to: 'home'
action:
- service: input_select.select_option
  data:
    entity_id: !input rich_selector
    option: Just Arrived
