blueprint:
  name: Mark as Home
  description: Make Presence detection not so Binary - Home.
  domain: automation
  source_url: https://github.com/tomerghelber/homeassistant/edit/main/blueprints/not_binary_presence_detection_home.yaml
  input:
    rich_selector:
      name: Rich Location Selector
      selector:
        target:
          entity:
            domain: input_select
    wait_before_home:
      name: Wait Before Home
      description: How much to wait before changing to home in minutes.
      selector:
        number:
          min: 1
          max: 15
          unit_of_measurement: minutes

trigger:
- platform: state
  entity_id: !input rich_selector
  to: 'Just Arrived'
  for:
    minutes: !input wait_before_home
action:
- service: input_select.select_option
  data_template:
    entity_id: !input rich_selector
    option: >
      {% if rich_selector == 'Just Left' %}
        Home
      {% else %}
        Just Arrived
      {% endif %}
