blueprint:
  name: Mark as Just Left
  description: Make Presence detection not so Binary - Just Left.
  domain: automation
  input:
    tracker:
      name: Tracker
      selector:
        entity:
          domain: device_tracker
    rich_selector:
      name: Rich Location Selector
      selector:
        target:
          entity:
            domain: input_select

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input tracker
  from: 'home'
  to: 'not_home'
action:
- service: input_select.select_option
  data:
    entity_id: !input rich_selector
    option: Just Left
