blueprint:
  name: Alarm Door Open
  description: Send a notification to a device when a door is opened and no one is there.
  domain: automation
  input:
    door_sensor:
      name: Door Sensor
      selector:
        entity:
          domain: binary_sensor
    rich_selector:
      name: Rich Location Selector
      selector:
        target:
          entity:
            domain: input_select
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app

trigger:
  platform: state
  entity_id: !input door_sensor
  to: 'on'

condition:
  condition: or
  conditions:
    - condition: template
      value_template: "{{ rich_selector == 'Away' }}"
    - condition: template
      value_template: "{{ rich_selector == 'Extended Away' }}"

action:
  domain: mobile_app
  type: notify
  device_id: !input notify_device
  message: "Door was Opened"
